name-template: 'Release v$NEXT_PATCH_VERSION'
tag-template: "$RESOLVED_VERSION"
change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending

categories:
  - title: "🚨 Breaking changes"
    labels:
      - "breaking-change"
  - title: "✨ New features"
    labels:
      - "new-feature"
  - title: "🐛 Bug fixes"
    labels:
      - "bugfix"
  - title: "🚀 Enhancements"
    labels:
      - "enhancement"
      - "refactor"
      - "performance"
  - title: "🧰 Maintenance"
    labels:
      - "maintenance"
      - "ci"
  - title: "📚 Documentation"
    labels:
      - "documentation"
  - title: "⬆️ Dependency updates"
    collapse-after: 5
    labels:
      - "dependencies"
  - title: "🚨🚨 Security Fixes 🚨🚨"
    labels:
      - "security"

exclude-labels:
  - "sync"

version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
  minor:
    labels:
      - "minor"
      - "new-feature"
  patch:
    labels:
      - "bugfix"
      - "chore"
      - "ci"
      - "dependencies"
      - "documentation"
      - "enhancement"
      - "performance"
      - "refactor"
      - "security"
  default: patch
no-changes-template: '- No changes'
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/huizebruin/s0tool/compare/$PREVIOUS_TAG...$RESOLVED_VERSION

   _To receive a notification on new releases, click on **Watch** > **Custom** > **Releases** on the top._

   _Be sure to 🌟 this repository for updates! _
   _Its a hobby project . Flash it go to the link http://s0tool.nl/Installation.html_