name-template: 'Release v$NEXT_PATCH_VERSION'
tag-template: "$RESOLVED_VERSION"
change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending

categories:
  - title: "🚨 Breaking changes"
    labels:
      - "breaking-change"
  - title: "✨ New features"
    labels:
      - "new-feature"
  - title: "🐛 Bug fixes"
    labels:
      - "bugfix"
  - title: "🚀 Enhancements"
    labels:
      - "enhancement"
      - "refactor"
      - "performance"
  - title: "🧰 Maintenance"
    labels:
      - "maintenance"
      - "ci"
  - title: "📚 Documentation"
    labels:
      - "documentation"
  - title: "⬆️ Dependency updates"
    collapse-after: 5
    labels:
      - "dependencies"
  - title: "🚨🚨 Security Fixes 🚨🚨"
    labels:
      - "security"

exclude-labels:
  - "sync"

version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
  minor:
    labels:
      - "minor"
      - "new-feature"
  patch:
    labels:
      - "bugfix"
      - "chore"
      - "ci"
      - "dependencies"
      - "documentation"
      - "enhancement"
      - "performance"
      - "refactor"
      - "security"
  default: patch
no-changes-template: '- No changes'
template: |
  ## What's Changed

  $CHANGES

  ## 💖 Support This Project
  If you find S0tool useful, consider supporting development:

  [![PayPal](https://img.shields.io/badge/send%20me%20a%20small%20gift-paypal-blue.svg?style=flat-square)](https://paypal.me/huizebruin)
  [![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/W7W4QU9ZX)

  #### Community Contributions
  We encourage all community members to contribute to the development of s0tool! Whether you have ideas for new features, want to help improve the documentation, or can contribute to our website, your input is valuable. Together, we can create an amazing tool!

  #### Ways to Contribute
  - **Code Contributions:** Feel free to submit pull requests or open issues with suggestions.
  - **Improving Documentation:** Help us by creating or enhancing the documentation for s0tool.
  - **Website Contributions:** If you have suggestions for website improvements, let us know!

  **Other ways to support:**
  - 🌟 Star this repository
  - 📢 Share with others
  - 💬 Join our Dutch Discord but have a s0tool english room too [Discord](https://discord.gg/AskpfnY)

  ---

  **Full Changelog**: https://github.com/huizebruin/s0tool/compare/$PREVIOUS_TAG...$RESOLVED_VERSION

   _To receive a notification on new releases, click on **Watch** > **Custom** > **Releases** on the top._

   _Be sure to 🌟 this repository for updates! _
   _Its a hobby project . Flash it go to the link http://s0tool.nl/Installation.html_