---
name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
sort-direction: ascending


categories:
  - title: "ðŸš¨ Breaking changes"
    labels:
      - "breaking-change"
  - title: "âœ¨ New features"
    labels:
      - "new-feature"
  - title: "ðŸ› Bug fixes"
    collapse-after: 8
    labels:
      - "bugfix"
  - title: "ðŸš€ Enhancements"
    collapse-after: 
    labels:
      - "enhancement"
      - "refactor"
      - "performance"
  - title: "ðŸ§° Maintenance"
    collapse-after: 6
    labels:
      - "maintenance"
      - "ci"
  - title: "ðŸ“š Documentation"
    labels:
      - "documentation"
  - title: "â¬†ï¸ Dependency updates"
    collapse-after: 6
    labels:
      - "dependencies"

exclude-labels:
  - "sync"

version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
  minor:
    labels:
      - "minor"
      - "new-feature"
  patch:
    labels:
      - "bugfix"
      - "chore"
      - "ci"
      - "dependencies"
      - "documentation"
      - "enhancement"
      - "performance"
      - "refactor"
  default: patch

template: |
  ## What's changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION

   **Contributors**: $CONTRIBUTORS

  **Total PRs Merged**: $NUMBER	