name: "Bug report"
description: "Create a bug report to help us improve the S0tool!"
labels: ["bug", "question", "triage:not-checked"]
body:
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "Please verify that this bug has NOT been raised before."
      description: "Search in the issues sections by clicking [HERE](https://github.com//samimasad/s0tool_detectleak/issues?q=) and read the [Discussions](https://github.com/samimasad/s0tool_detectleak/discussions)!"
      options:
        - label: "I checked and didn't find a similar issue"
          required: true
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Describe the bug*"
      description: "A clear and concise description of what the bug is."
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: "Expected behaviour"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "..."
  - type: textarea
    id: version-info
    validations:
      required: true
    attributes:
      label: "Version Information"
      description: "The version info block."
      placeholder: "Please post S0tool version / ESPHome version / Home Assistant version "
  - type: textarea
    id: esphome-version-info
    validations:
      required: true
    attributes:
      label: "ESPHome version Information"
      description: "The version info block."
      placeholder: "Please post ESPHome version"
  - type: textarea
    id: home-assistant-version-info
    validations:
      required: true
    attributes:
      label: "Home Assistant version Information"
      description: "The version info block."
      placeholder: "Please post Home Assistant version "

  - type: textarea
    id: additional-context
    validations:
      required: true
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here."
      placeholder: "Add any other context about the problem here. "

