name: Build

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      bypass-yaml-check:
        description: 'Bypass YAML change check (force build/publish)'
        type: boolean
        required: false
        default: false
  release:
    types: [published]

jobs:
  build-and-publish:
    uses: ./.github/workflows/reusable-build.yml
    with:
      device-name: s0tool
      yaml-files: |
        esphome/watermeter.yaml
        esphome/pulscounter.yaml
        esphome/S0-puls-kwhpuls.yaml
        esphome/S0-puls-DSZ12D.yaml
        esphome/S0-puls-LEM022SJ.yaml
        esphome/s0-watermeter.yaml
        esphome/wsz15d32a.yaml
        esphome/sdm72d.yaml
        esphome/puls-water-internal.yaml
        esphome/kwh-water-test.yaml
        esphome/pulscounter_flux.yaml
      esphome-version: 2026.8.0
      check-yaml-changes: ${{ !(github.event_name == 'workflow_dispatch' && github.event.inputs.bypass-yaml-check == 'true') }}
      publish-to-pages: true
      has-installer: true
      installer-path: static